services:
  streamlit-frontend:
    image: anazmuhdd/guardrails-ai:latest
    build:
      context: .
      args:
        - GUARDRAILS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXRodWJ8MTYwOTQxMjczIiwiYXBpS2V5SWQiOiJhMzAzZWFjMy05Yzg1LTQ4NzctOWUwOC0xMzNkMDZlZjBjZTEiLCJzY29wZSI6InJlYWQ6cGFja2FnZXMiLCJwZXJtaXNzaW9ucyI6W10sImlhdCI6MTc2NTg4NjQxOSwiZXhwIjoxNzczNjYyNDE5fQ.oefbRysj4x0SmIoIA4KcehFD1Vd6DIfVQm6JYPNUJSc
    container_name: guardrails-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: >
      streamlit run main.py
    restart: unless-stopped

  guardserver:
    image: anazmuhdd/guardrails-ai:latest
    build:
      context: .
      args:
        - GUARDRAILS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXRodWJ8MTYwOTQxMjczIiwiYXBpS2V5SWQiOiJhMzAzZWFjMy05Yzg1LTQ4NzctOWUwOC0xMzNkMDZlZjBjZTEiLCJzY29wZSI6InJlYWQ6cGFja2FnZXMiLCJwZXJtaXNzaW9ucyI6W10sImlhdCI6MTc2NTg4NjQxOSwiZXhwIjoxNzczNjYyNDE5fQ.oefbRysj4x0SmIoIA4KcehFD1Vd6DIfVQm6JYPNUJSc
    container_name: guardrails-guardserver
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      python -c "import os;from dotenv import load_dotenv;load_dotenv();import uvicorn;uvicorn.run('guardserver:app', host='0.0.0.0', port=5000, log_level='info')"
    restart: unless-stopped

  modelserv:
    image: anazmuhdd/guardrails-ai:latest
    build:
      context: .
      args:
        - GUARDRAILS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXRodWJ8MTYwOTQxMjczIiwiYXBpS2V5SWQiOiJhMzAzZWFjMy05Yzg1LTQ4NzctOWUwOC0xMzNkMDZlZjBjZTEiLCJzY29wZSI6InJlYWQ6cGFja2FnZXMiLCJwZXJtaXNzaW9ucyI6W10sImlhdCI6MTc2NTg4NjQxOSwiZXhwIjoxNzczNjYyNDE5fQ.oefbRysj4x0SmIoIA4KcehFD1Vd6DIfVQm6JYPNUJSc
    container_name: guardrails-modelserv
    ports:
      - "8001:8000"
    env_file:
      - .env
    command: >
      python -c "import os;from dotenv import load_dotenv;load_dotenv();import uvicorn;host = os.getenv('HOST', '0.0.0.0');port = int(os.getenv('PORT', '8000'));uvicorn.run('modelserv:app', host=host, port=port, log_level='info')"
    restart: unless-stopped